name: Build and Release Electron App

on:
  push:
    branches:
      - main # only run on main
    tags:
      - "v*.*.*" # only version tags like v1.0.0

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build Electron App
        run: pnpm run dist # assumes "dist" script is set in package.json

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: electron-artifacts
          path: dist/**/*

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          files: dist/**/* # attach all build files
