name: Build and Release Monorepo

on:
  push:
    tags:
      - "v*.*.*" # triggers on semantic version tags like v1.0.0

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      # ------------------------------
      # Build Core package
      # ------------------------------
      - name: Build Core Package
        run: pnpm --filter core run build

      # ------------------------------
      # Build Desktop App
      # ------------------------------
      - name: Build Desktop App
        run: pnpm --filter desktop-app run build

      - name: List Desktop App dist for debugging
        run: ls -R packages/desktop-app/dist

      - name: Package Desktop App
        run: pnpm --filter desktop-app run dist

      # ------------------------------
      # Build CLI
      # ------------------------------
      - name: Build CLI
        run: pnpm --filter cli run build

      - name: Package CLI
        run: pnpm --filter cli run dist

      # ------------------------------
      # Upload Artifacts
      # ------------------------------
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: all-artifacts
          path: |
            packages/core/dist/**
            packages/desktop-app/release/**   # electron-builder output folder
            packages/cli/dist/**

      # ------------------------------
      # Create GitHub Release
      # ------------------------------
      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          artifacts: all-artifacts
          token: ${{ secrets.GITHUB_TOKEN }}
