name: Build and Release Monorepo

on:
  push:
    branches:
      - main
    tags:
      - "v*.*.*"

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build Core Package
        run: pnpm --filter core run build

      - name: Build Desktop App
        run: pnpm --filter desktop-app run dist

      - name: Build CLI
        run: pnpm --filter cli run dist

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: all-artifacts
          path: |
            packages/core/dist/**
            packages/desktop-app/dist/**
            packages/cli/dist/**

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          files: |
            packages/core/dist/**
            packages/desktop-app/dist/**
            packages/cli/dist/**
